"""Create messages table

Revision ID: 5ffd5ebf56c9
Revises: 29009a5c4969
Create Date: 2025-01-23 15:43:14.082010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffd5ebf56c9'
down_revision = '29009a5c4969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
